<?hh // strict

/**
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * This software consists of voluntary contributions made by many individuals
 * and is licensed under the MIT license.
 *
 * Copyright (c) 2017-2018 Yuuki Takezawa
 *
 */
namespace Ytake\HHConfigAggreagator;

class ConfigAggreagator {
  const string ENABLE_CACHE = 'config_cache_enabled';
  private array<mixed, mixed> $config = [];

  public function __construct(
    array<ConfigProvidable> $providers = [],
    ?string $cachedConfigFile = null,
  ) {
    if ($this->loadConfigFromCache($cachedConfigFile)) {
      return;
    }
    $this->config = $this->loadConfigFromProviders($providers)->toArray();
    $this->cacheConfig($this->config, $cachedConfigFile);
  }

  private function loadConfigFromCache(?string $cachedConfigFile): bool {
    if (null === $cachedConfigFile) {
      return false;
    }
    $require = new Filesystem($cachedConfigFile);
    if (!$require->exists()) {
      return false;
    }
    $this->config = $require->require();
    return true;
  }

  private function loadConfigFromProviders(
    array<ConfigProvidable> $providers,
  ): Map<mixed, mixed> {
    $mergedConfig = [];
    $configArray = Vector{};
    foreach ($providers as $provider) {
      $configArray->add($provider->provide());
    }
    return $this->mergeArrayToMap($configArray);
  }

  private function mergeArrayToMap(
    Vector<array<mixed, mixed>> $vec
  ): Map<mixed, mixed> {
    $map = Map {};
    foreach ($vec as $v) {
      if (is_array($v)) {
        foreach ($v as $key => $row) {
          if (is_int($key) || is_string($key)) {
            $map->add(Pair {$key, $row});
          }
        }
      }
    }
    return $map;
  }

  /**
   * @return array<mixed, mixed>
   */
  public function getMergedConfig(): array<mixed, mixed> {
    return $this->config;
  }

  protected function cacheConfig(
    array<mixed, mixed> $configMap,
    ?string $cachedConfigFile = null,
  ): void {
    if (null === $cachedConfigFile) {
      return;
    }
    if (!array_key_exists(static::ENABLE_CACHE, $configMap)) {
      return;
    }
    if (!$configMap[static::ENABLE_CACHE]) {
      return;
    }
    file_put_contents(
      $cachedConfigFile,
      sprintf(
        '<?hh
        /**
        * This configuration cache file was generated by %s
        * at %s
        */
        return %s;',
        get_class($this),
        date('c'),
        var_export($configMap, true),
      ),
    );
    return;
  }
}
